window.portfolioData = {
    projects: [
        { id: "merchandising-agent", number: "01", category: "AI & Retail Ops", title: "Merchandising Agent", description: "A retail intelligence system that monitors sales performance, detects excess stock and stockout risk, and recommends pricing actions using transparent decision logic.", image: "images/retail-dashboard.svg", tags: ["Python", "Analytics", "Retail AI", "Dashboard"] },
        { id: "india-strategy", number: "02", category: "Transformation Strategy", title: "India Strategic Program", description: "A market transformation program designed to reignite growth, rebuild consumer trust, and align brand, retail, digital, and commercial priorities across India.", image: "images/india-strategy.png", tags: ["Strategy", "Growth", "Transformation", "India"] },
        { id: "own-retail", number: "03", category: "Retail Strategy", title: "Own Retail Channel Launch", description: "A mono-branded retail channel launch that strengthened brand authority, elevated customer experience, and gave franchise partners a scalable operating model to follow.", image: "images/own-retail.png", tags: ["Retail", "Channel Launch", "Operations", "Brand"] },
        { id: "export-channel", number: "04", category: "Operating Model", title: "Export Channel Establishment", description: "An integrated export operations framework across Nepal, Bhutan, Bangladesh, Sri Lanka, and the Maldives, connecting reporting, training, merchandising, and collaboration.", image: "images/export-channel.png", tags: ["Export", "Operations", "Merchandising", "Collaboration"] },
        { id: "ecom-launch", number: "05", category: "Digital Commerce", title: "eCom Launch", description: "A digital commerce launch that connected consumer research, ERP and payment integrations, mobile-first experience, and a new direct-to-consumer growth channel.", image: "images/ecom-launch.png", tags: ["eCommerce", "Digital", "D2C", "Launch"] },
        { id: "lena-organization", number: "06", category: "Organization Design", title: "LENA Organization Design", description: "An organization design engagement that clarified roles, decision rights, and collaboration systems so a growing team could move with more focus and less friction.", image: "images/lena-organization.png", tags: ["Organization Design", "Operating Model", "Leadership", "Collaboration"] }
    ],
    posts: [
        { date: "23 Sep 2026", category: "AI product", title: "Building a merchandising agent for retail decision-making", excerpt: "An AI-assisted merchandising workflow that turns sales and inventory signals into clear recommendations for pricing, stock health, and operational focus." }
    ]
};
