window.portfolioData = {
    projects: [
        { id: "merchandising-agent", number: "01", category: "AI & Retail Ops", title: "Merchandising Agent", description: "A retail intelligence system that monitors sales performance, detects excess stock and stockout risk, and recommends pricing actions using transparent decision logic.", image: "images/retail-dashboard.svg", tags: ["Python", "Analytics", "Retail AI", "Dashboard"] },
        { id: "india-strategy", number: "02", category: "Transformation Strategy", title: "India Strategic Program", description: "A market transformation program designed to reignite growth, rebuild consumer trust, and position the brand as a market leader.", copy: ["The program brought together brand positioning, channel optimization, retail execution, and digital acceleration across India.", "The work translated consumer and market insight into a practical strategic framework, aligning leadership, commercial, retail, marketing, and technology teams around shared priorities.", "The result was a clearer growth agenda, stronger cross-functional governance, and a foundation for consistent execution across markets."], image: "images/india-strategy.png", gallery: ["images/india-01.png", "images/india-02.png", "images/india-03.png", "images/india-04.png"], tags: ["Strategy", "Growth", "Transformation", "India"] },
        { id: "own-retail", number: "03", category: "Retail Strategy", title: "Own Retail Channel Launch", description: "A mono-branded retail channel launch that strengthened brand authority, elevated customer experience, and gave franchise partners a scalable operating model.", copy: ["The initiative launched a direct retail channel in India to land the brand with authority, create a more consistent consumer experience, and inspire franchise partners to raise performance.", "The approach connected retail development, merchandising, marketing, IT, finance, HR, and legal workstreams through global POS and ERP systems.", "The retail channel created a scalable foundation for direct consumer engagement, stronger brand visibility, and more consistent execution across key urban markets."], image: "images/own-retail.png", gallery: ["images/own-retail-01.png", "images/own-retail-02.png", "images/own-retail-03.png", "images/own-retail-04.png", "images/own-retail-05.png", "images/own-retail-06.png", "images/own-retail-07.jpg"], tags: ["Retail", "Channel Launch", "Operations", "Brand"] },
        { id: "export-channel", number: "04", category: "Operating Model", title: "Export Channel Establishment", description: "An integrated export operations framework across Nepal, Bhutan, Bangladesh, Sri Lanka, and the Maldives, connecting reporting, training, merchandising, and collaboration.", copy: ["The export business faced growing complexity in product flow, market reporting, and partner coordination across neighbouring countries.", "The solution established a centralized operating function with standardized reporting, training, merchandising, and digital collaboration tools that made sellout and market performance more visible.", "The work reduced operational inefficiencies, improved data accuracy by 40%, strengthened brand consistency across export markets, and shortened decision cycles through real-time tracking."], image: "images/export-channel.png", gallery: ["images/export-channel-01.png", "images/export-channel-02.png", "images/export-channel-03.png"], tags: ["Export", "Operations", "Merchandising", "Collaboration"] },
        { id: "ecom-launch", number: "05", category: "Digital Commerce", title: "eCom Launch", description: "A digital commerce launch that connected consumer research, ERP and payment integrations, mobile-first experience, and a new direct-to-consumer growth channel.", copy: ["The brand wanted to launch an eCom channel in a key geography as consumers shifted toward online purchasing and mobile-first engagement.", "The project moved through discovery, development, testing, and launch, combining consumer workshops, competitive benchmarking, user-journey design, and cross-functional delivery.", "The channel went live on time and created a new source of revenue, customer data, loyalty, and future omnichannel opportunities such as click and collect and in-store digital experiences."], image: "images/ecom-launch.png", gallery: ["images/ecom-launch-01.png", "images/ecom-launch-02.png", "images/ecom-launch-03.png", "images/ecom-launch-04.png", "images/ecom-launch-05.png"], tags: ["eCommerce", "Digital", "D2C", "Launch"] },
        { id: "lena-organization", number: "06", category: "Organization Design", title: "LENA Organization Design", description: "An organization design engagement that clarified roles, decision rights, and collaboration systems so a growing team could move with more focus and less friction.", copy: ["The work focused on creating a clearer organization model for a growing business, with the right interfaces between leadership, markets, and functional teams.", "The engagement connected organization design with governance, collaboration, culture building, and practical operating rhythms rather than treating structure as an isolated exercise.", "The result was a more aligned team, stronger cross-market knowledge sharing, and a clearer foundation for sustainable growth."], image: "images/lena-organization.png", gallery: ["images/lena-organization-01.png", "images/lena-organization-02.png", "images/lena-organization-03.png", "images/lena-organization-04.png", "images/lena-organization-05.png", "images/lena-organization-06.png", "images/lena-organization-07.png"], tags: ["Organization Design", "Operating Model", "Leadership", "Collaboration"] }
    ],
    posts: [
        { date: "23 Sep 2026", category: "AI product", title: "Building a merchandising agent for retail decision-making", excerpt: "An AI-assisted merchandising workflow that turns sales and inventory signals into clear recommendations for pricing, stock health, and operational focus." }
    ]
};
